Refactor constants to file
MariMountaineers/stream-reactor pull request #14
Opened 2017-04-10 16:21 UTC by goncaloccastro

2017-04-10 16:25 UTC, pedrobento988 approved these changes

2017-04-10 16:36 UTC, fartariatomas approved these changes

2017-04-10 16:36 UTC, fartariatomas commented on kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSinkConfigConstants.scala
> +  val ERROR_POLICY_DOC: String = "Specifies the action to be taken if an error occurs while inserting the data.\n" +
should be a multi-line string

2017-04-10 17:10 UTC, pedrobento988 requested changes

2017-04-10 17:10 UTC, pedrobento988 commented on kafka-connect-mongodb/src/main/scala/com/datamountaineer/streamreactor/connect/mongodb/config/MongoSinkConfigConstants.scala
> +    """.stripMargin
You added a new line here, which was not in the original file

2017-04-11 08:39 UTC, pedrobento988 approved these changes

2017-04-11 09:07 UTC, merged