Fix/refactor cassandra connector 28
MariMountaineers/stream-reactor pull request #33
Opened 2017-04-21 15:17 UTC by pedrobento988

Consistency Level Settings created.

2017-04-21 15:37 UTC, carolinaloureiro requested changes
make some changes, but looks good

2017-04-21 15:37 UTC, carolinaloureiro commented on kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraConfig.scala
> +import com.datamountaineer.streamreactor.temp._
we against this, no wildcards

2017-04-21 15:37 UTC, carolinaloureiro commented on kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
> -import scala.util.{Failure, Success, Try}
same as above

2017-04-21 15:37 UTC, carolinaloureiro commented on kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
> +    val threadPoolSize: Int = config.getThreadPoolSize
no need for the : Int

2017-04-21 15:37 UTC, carolinaloureiro commented on kafka-connect-temp/src/main/scala/com/datamountaineer/streamreactor/temp/ConsistencyLevelSettings.scala
> +
delete extra line

2017-04-21 15:37 UTC, carolinaloureiro commented on kafka-connect-temp/src/main/scala/com/datamountaineer/streamreactor/temp/ConsistencyLevelSettings.scala
> +  def getConsistencyLevel[T <: Enum[T]](clazz: Class[T]): Option[T] = {
change clazz

2017-04-21 15:38 UTC, fartariatomas requested changes

2017-04-21 15:38 UTC, fartariatomas commented on kafka-connect-temp/src/main/scala/com/datamountaineer/streamreactor/temp/ConsistencyLevelSettings.scala
> +  def getConsistencyLevel[T <: Enum[T]](clazz: Class[T]): Option[T] = {
what is clazz? pick a better name

2017-04-21 15:38 UTC, fartariatomas commented on kafka-connect-temp/src/main/scala/com/datamountaineer/streamreactor/temp/ConsistencyLevelSettings.scala
> +          case Failure(e) => throw new ConfigException(s"'$other' is not a valid $consistencyLevelConstant. " +
this string should be replaced with a multi-line string. use .stripMargin.replaceAll("\n","") to make multiline strings with no new lines

2017-04-21 15:42 UTC, fartariatomas commented on kafka-connect-cassandra/src/main/scala/com/datamountaineer/streamreactor/connect/cassandra/config/CassandraSettings.scala
> +    val consistencyLevel = config.getConsistencyLevel(classOf[ConsistencyLevel])
This deserves a comment to explain why you are passing the classOf instead of a variable

2017-04-21 18:52 UTC, h314to commented on kafka-connect-temp/src/main/scala/com/datamountaineer/streamreactor/temp/ConsistencyLevelSettings.scala
> +          case Failure(e) => throw new ConfigException(s"'$other' is not a valid $consistencyLevelConstant. " +
It's just two lines. Doing multiline -> stripmargin -> replace("\n","") seems a bit less legible than just continuing on the next line.

2017-04-24 08:30 UTC, fartariatomas commented on kafka-connect-temp/src/main/scala/com/datamountaineer/streamreactor/temp/ConsistencyLevelSettings.scala
> +          case Failure(e) => throw new ConfigException(s"'$other' is not a valid $consistencyLevelConstant. " +
It's still ugly but ok

2017-04-24 08:34 UTC, fartariatomas approved these changes
Looking good

2017-04-24 08:45 UTC, joseluisvf approved these changes

2017-04-24 08:45 UTC, carolinaloureiro approved these changes
I like this solution! Well done

2017-04-24 08:57 UTC, merged