Refactor constants to separate file
MariMountaineers/stream-reactor pull request #7
Opened 2017-04-10 15:39 UTC by fartariatomas

2017-04-10 15:43 UTC, pedrobento988 approved these changes

2017-04-10 16:39 UTC, carolinaloureiro approved these changes
too many blank spaces but ok

2017-04-10 17:03 UTC, pedrobento988 requested changes

2017-04-10 17:03 UTC, pedrobento988 commented on kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/config/HbaseSinkConfigConstants.scala
> +      |THROW - the error is allowed to propagate. \n
please remove \n

2017-04-10 17:03 UTC, pedrobento988 commented on kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/config/HbaseSinkConfigConstants.scala
> +    """
Your are inserting a new empty line

2017-04-10 17:03 UTC, pedrobento988 commented on kafka-connect-hbase/src/main/scala/com/datamountaineer/streamreactor/connect/hbase/config/HbaseSinkConfigConstants.scala
> +    """.stripMargin
Your are inserting a new empty line

2017-04-11 08:39 UTC, pedrobento988 approved these changes

2017-04-11 09:18 UTC, merged